name: 抢购多点优惠券
on:
  push:
    branches: [ master ]
  schedule:
    # 定时任务，在每天的5点执行任务
    - cron: '55 23 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: clone script
        run: wget http://49.233.24.188/assets/dd_client.py -O /tmp/dd_client.py
      - name: execute script
        run: python3 /tmp/dd_client.py 1 
