name: 抢购多点优惠券
on:
  push:
    branches: [ master ]
  schedule:
    # 定时任务，在每天的5点执行任务
    - cron: '55 23 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: clone script
        run: wget http://49.233.24.188/assets/ddyhqd.sh -O /tmp/ddyhqd.sh
      - name: execute script
        run: sh -x /tmp/ddyhqd.sh
